packages:
  - .
  - playground/*
catalogs:
  build:
    tsdown: ^0.12.9
    vite: ^7.0.2
  cli:
    bumpp: ^10.2.0
    czg: ^1.11.2
    pncat: ^0.2.6
    taze: ^19.1.0
  common-plugin:
    '@originjs/vite-plugin-federation': ^1.4.1
    rollup-plugin-visualizer: ^6.0.3
    vite-plugin-dts: ^4.5.4
    vite-plugin-dynamic-base: ^1.2.0
    vite-plugin-jspm: ^0.6.1
  dev:
    '@jspm/generator': ^2.6.2
    '@octohash/tsconfig': ^0.1.0
    typescript: ^5.8.3
  lint:
    '@antfu/eslint-config': ^4.16.2
    eslint: ^9.30.1
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
  node:
    '@clack/prompts': ^0.11.0
    fast-glob: ^3.3.3
    find-up: ^7.0.0
    local-pkg: ^1.1.1
    pkg-types: ^2.2.0
  test:
    vitest: ^3.2.4
  types:
    '@types/node': ^22.16.0
  utils:
    '@antfu/install-pkg': ^1.1.0
    dayjs: ^1.11.13
    deepmerge: ^4.3.1
  vue-plugin:
    '@intlify/unplugin-vue-i18n': ^6.0.8
    '@vitejs/plugin-vue': ^6.0.0
    '@vitejs/plugin-vue-jsx': ^5.0.1
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.8.0
    unplugin-vue-router: ^0.14.0
    vite-plugin-vue-devtools: ^7.7.7
