packages: []
catalogs:
  build:
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.3.1
    pncat: ^0.7.3
    taze: ^19.8.1
  common:
    '@originjs/vite-plugin-federation': ^1.4.1
    rollup-plugin-visualizer: ^6.0.5
    vite-plugin-dts: ^4.5.4
    vite-plugin-dynamic-base: ^1.2.0
    vite-plugin-jspm: ^0.6.1
  dev:
    '@jspm/generator': ^2.7.4
  lint:
    '@antfu/eslint-config': ^6.0.0
    eslint: ^9.38.0
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  node:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    find-up: ^8.0.0
    local-pkg: ^1.1.2
    pathe: ^2.0.3
    pkg-types: ^2.3.0
    tinyglobby: ^0.2.15
  test:
    vitest: ^4.0.1
  tsc:
    typescript: ^5.9.3
  types:
    '@types/node': ^24.9.1
  utils:
    dayjs: ^1.11.18
    deepmerge: ^4.3.1
  vue:
    '@intlify/unplugin-vue-i18n': ^11.0.1
    '@vitejs/plugin-vue': ^6.0.1
    '@vitejs/plugin-vue-jsx': ^5.1.1
    unplugin-auto-import: ^20.2.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-router: ^0.16.0
    vite-plugin-vue-devtools: ^8.0.3
