packages:
  - .
  - playground/*
catalogs:
  build:
    tsdown: ^0.12.4
    vite: ^6.3.5
  cli:
    bumpp: ^10.1.1
    czg: ^1.11.1
    pncat: ^0.2.4
    taze: ^19.1.0
  common-plugin:
    '@originjs/vite-plugin-federation': ^1.4.1
    rollup-plugin-visualizer: ^6.0.1
    vite-plugin-dts: ^4.5.4
    vite-plugin-dynamic-base: ^1.1.0
    vite-plugin-jspm: ^0.6.1
  dev:
    '@jspm/generator': ^2.6.1
    '@octohash/tsconfig': ^0.1.0
    typescript: ^5.8.3
  lint:
    '@antfu/eslint-config': ^4.13.2
    eslint: ^9.27.0
    lint-staged: ^16.1.0
    simple-git-hooks: ^2.13.0
  node:
    '@clack/prompts': ^0.11.0
    fast-glob: ^3.3.3
    find-up: ^7.0.0
    local-pkg: ^1.1.1
    pkg-types: ^2.1.0
  test:
    vitest: ^3.1.4
  types:
    '@types/node': ^22.15.23
  utils:
    '@antfu/install-pkg': ^1.1.0
    dayjs: ^1.11.13
    deepmerge: ^4.3.1
  vue-plugin:
    '@intlify/unplugin-vue-i18n': ^6.0.8
    '@vitejs/plugin-vue': ^5.2.4
    '@vitejs/plugin-vue-jsx': ^4.2.0
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.7.0
    unplugin-vue-router: ^0.12.0
    vite-plugin-vue-devtools: ^7.7.6
