minimumReleaseAgeExclude:
  - '@octohash/eslint-config@0.4.1'
packages: []
allowBuilds:
  '@swc/core': true
  esbuild: true
  simple-git-hooks: true
catalogs:
  build:
    tsdown: ^0.22.3
  common-plugin:
    unplugin-auto-import: ^21.0.0
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-dts: ^5.0.3
    vite-plugin-dynamic-base: ^1.4.1
  dev:
    bumpp: ^11.1.0
    nano-staged: ^1.0.2
    pncat: ^0.12.0
    simple-git-hooks: ^2.13.1
    taze: ^19.14.1
    typescript: ^6.0.3
  inlined:
    deepmerge: ^4.3.1
    empathic: ^2.0.1
    local-pkg: ^1.2.1
    pathe: ^2.0.3
    pkg-types: ^2.3.1
  lint:
    '@octohash/eslint-config': ^0.4.1
    eslint: ^10.5.0
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^1.6.0
  test:
    vitest: ^4.1.9
  types:
    '@types/node': ^26.0.1
  vue-plugin:
    '@intlify/unplugin-vue-i18n': ^11.2.4
    '@vitejs/plugin-vue': ^6.0.7
    '@vitejs/plugin-vue-jsx': ^5.1.6
    unplugin-vue-components: ^32.1.0
    vite-plugin-vue-devtools: ^8.1.4
    vue-router: ^5.1.0
