packages:
  - .
  - playground/*
catalogs:
  build:
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.2.3
    pncat: ^0.5.0
    taze: ^19.3.0
  common:
    '@originjs/vite-plugin-federation': ^1.4.1
    rollup-plugin-visualizer: ^6.0.3
    vite-plugin-dts: ^4.5.4
    vite-plugin-dynamic-base: ^1.2.0
    vite-plugin-jspm: ^0.6.1
  dev:
    '@jspm/generator': ^2.6.4
    '@octohash/tsconfig': ^0.2.0
    typescript: ^5.9.2
  lint:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.34.0
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
  node:
    '@clack/prompts': ^0.11.0
    find-up: ^7.0.0
    local-pkg: ^1.1.2
    pkg-types: ^2.3.0
    tinyglobby: ^0.2.14
  test:
    vitest: ^3.2.4
  types:
    '@types/node': ^24.3.0
  utils:
    '@antfu/install-pkg': ^1.1.0
    dayjs: ^1.11.15
    deepmerge: ^4.3.1
  vue:
    '@intlify/unplugin-vue-i18n': ^6.0.8
    '@vitejs/plugin-vue': ^6.0.1
    '@vitejs/plugin-vue-jsx': ^5.1.1
    unplugin-auto-import: ^20.1.0
    unplugin-vue-components: ^29.0.0
    unplugin-vue-router: ^0.15.0
    vite-plugin-vue-devtools: ^8.0.1
