catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

packages: []
catalogs:
  build:
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.3.2
    pncat: ^0.7.7
    taze: ^19.9.2
  common:
    '@originjs/vite-plugin-federation': ^1.4.1
    unplugin-auto-import: ^20.3.0
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-dts: ^4.5.4
    vite-plugin-dynamic-base: ^1.2.0
    vite-plugin-jspm: ^0.6.2
  dev:
    '@jspm/generator': ^2.8.0
  lint:
    '@antfu/eslint-config': ^6.6.1
    eslint: ^9.39.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  node:
    '@clack/prompts': ^0.11.0
    find-up: ^8.0.0
    pathe: ^2.0.3
    tinyglobby: ^0.2.15
  pkg:
    '@antfu/install-pkg': ^1.1.0
    local-pkg: ^1.1.2
    pkg-types: ^2.3.0
  test:
    vitest: ^4.0.15
  tsc:
    typescript: ^5.9.3
  types:
    '@types/node': ^24.10.2
  utils:
    dayjs: ^1.11.19
    deepmerge: ^4.3.1
  vue:
    '@intlify/unplugin-vue-i18n': ^11.0.1
    '@vitejs/plugin-vue': ^6.0.2
    '@vitejs/plugin-vue-jsx': ^5.1.2
    unplugin-vue-components: ^30.0.0
    unplugin-vue-router: ^0.19.0
    vite-plugin-vue-devtools: ^8.0.5
